
= Enohar Changelog

== Unreleased

* Able to resolve templated elements

== [[0.0-alpha.8.0]] - 2019-08-18

=== Changed

* Emits all eno elements, including children, rather than just the name of the parent.

== [[0.0-alpha.7.0]] - 2019-08-17

=== Added

* Recognizes bare names and exposes these via section.empty() or .empties().

== [[0.0-alpha.6.0]] - 2019-07-02

=== Added

* Exposes section.fields().fieldsets() etc, to get all elements of that type.
* Exposes deserialization via a new class, Eno.

=== Changed

* FieldList provides the combined items of itself and the template when it has a non-null reference.
* Section.element(name) gets an element of that name, rather than the first of that type.

== [[0.0-alpha.5.0]] - 2019-06-26

=== Added

* Depends on note\_enohaste for locale files, reflected in pom.xml

=== Removed

* Copies of locale files from resources (so as not to shadow the new jar).

== [[0.0-alpha.4.0]] - 2019-06-25

=== Changed

* Comments immediately preceeding set entry and list item associate with them, rather than the enclosing field.
* Comments at the start of the document with preceeding empty lines now associate with the first element, rather than the enclosing document. 
* Multiline is now a Value subclass, rather than Field subclass

== [[0.0-alpha.3.0]] - 2019-06-23

=== Changed

* Renames Semantologist as Grammarian.

== [[0.0-alpha.2.0]] - 2019-02-16

=== Added

* Tests for multiline and partial document (Which is to say, a compliant parser).

== [[0.0-alpha.1.0]] - 2018-02-02

=== Changed

* Lexer calculates divergence from section operator for same, not escapes (Which is to say, a compliant lexer).

// Added Changed Removed
